#  numpy套件

   <font color=Darkblue> 
    
### 矩陣 * 3

In [8]:
a_list=[1,2,3,4,5]
print(a_list*3)

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5]


<font color=Darkblue> 

### numpy 套件 ndarray 型態

In [9]:
#numpy 套件 ndarray 型態 ， 提供element-wise的操作
import numpy as np 
a_ndarray=np.array([1,2,3,4,5])
print(a_ndarray*3)

[ 3  6  9 12 15]


In [10]:
print(type(a_ndarray))
print(a_ndarray.ndim)  #ndarray的維度
print(a_ndarray.shape) #ndarray的shape
print(a_ndarray.dtype) #ndarray的資料型態


<class 'numpy.ndarray'>
1
(5,)
int32


In [11]:
z=np.zeros(6)
print(z) #六個元素都為0的1d ndarray
print(np.zeros((2,6))) #12個元素都為0的2d ndarray
print(np.empty((2,6,2))) #24個元素都未初始化的值
print(np.arange(10)) #10個元素為0-9的1d ndarray

[0. 0. 0. 0. 0. 0.]
[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]
[[[2.88854907e+214 1.81271043e-152]
  [5.72938864e-313 1.42990075e+248]
  [9.59836917e-312 4.83245960e+276]
  [2.65666903e-258 8.48798316e-313]
  [6.01346930e-154 9.59836685e-312]
  [7.34518269e+223 1.96086537e+243]]

 [[1.01855798e-312 7.27458162e+199]
  [9.59836917e-312 1.42990110e+248]
  [7.34483868e+223 2.33419537e-313]
  [1.96086509e+243 9.59836686e-312]
  [1.17076186e+214 6.01347002e-154]
  [4.45619116e-313 1.88891968e+219]]]
[0 1 2 3 4 5 6 7 8 9]


# numpy 的進階操作

In [12]:
my_array=np.arange(10)
print(my_array)
print(my_array[0])
print(my_array[0:5])

[0 1 2 3 4 5 6 7 8 9]
0
[0 1 2 3 4]


In [16]:
#2維numpy取值
my_2d_array = np.array ( [np.arange(0,5), np.arange(5,10)])
print(my_2d_array)
print(my_2d_array[1,:])#第二列的資料
print(my_2d_array[:,1])#第二欄的資料
print(my_2d_array[1,1])#第二列第二欄的資料
print(my_2d_array[1,2:])
print(my_2d_array[1,:3])
print(my_2d_array[1,1:-2])

[[0 1 2 3 4]
 [5 6 7 8 9]]
[5 6 7 8 9]
[1 6]
6
[7 8 9]
[5 6 7]
[6 7]


In [15]:
#假設有六個組別"Modern Web","Devops","cloud","big data","security","自我挑戰"
#其參加人數分別為56,8,19,14,6,71人
groups=["Modern Web","Devops","cloud","big data","security","自我挑戰"]
ironman=[ 56,8,19,14,6,71 ]
groups_array=np.array(groups)
ironman_array=np.array(ironman)
print(groups_array)
print(ironman_array)

['Modern Web' 'Devops' 'cloud' 'big data' 'security' '自我挑戰']
[56  8 19 14  6 71]


In [17]:
# 用人數去篩選組別
print(ironman_array>=10)
print(groups_array[ironman_array>=10])
print(groups_array != '自我挑戰')
print(ironman_array[groups_array != '自我挑戰'])

[ True False  True  True False  True]
['Modern Web' 'cloud' 'big data' '自我挑戰']
[ True  True  True  True  True False]
[56  8 19 14  6]


# Ndarray 轉置

In [18]:
my_1d_array=np.arange(10)
print(my_1d_array)
my_2d_array=my_1d_array.reshape((2,5))
print(my_2d_array)
print(my_2d_array.T)

[0 1 2 3 4 5 6 7 8 9]
[[0 1 2 3 4]
 [5 6 7 8 9]]
[[0 5]
 [1 6]
 [2 7]
 [3 8]
 [4 9]]


In [21]:
print(np.arange(24))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]


In [22]:
print(np.arange(24).reshape(4,6))

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]


In [19]:
#ndarray nan (空值)
nan_array =  np.array([56,8,19,14,6, np.nan ])
print(nan_array)

[56.  8. 19. 14.  6. nan]
